# Generated by Django 4.2.3 on 2023-07-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duhovnost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stihovi',
            name='objavljeno',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
